[versions]
activity = "1.11.0"
agp = "8.13.1"
appcompat = "1.6.1"
espressoCore = "3.5.1"
constraintlayout = "2.1.4"
glide = "5.0.5"
junit = "4.13.2"
junitVersion = "1.1.5"
material = "1.10.0"
recyclerview = "1.4.0"
preference = "1.2.0"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }